project:
  name: "OCP Meeting Api"
  author: "Pavel Shestakov"
  version: "0.0.1"

grpc:
  address: ":8082"

rest:
  address: ":8081"

database:
  host: "127.0.0.1"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "postgres"
  sslmode: "disable"
  driver: "postgres"


prometheus:
  uri: "/metrics"
  port: ":9100"

kafka:
  topic: "meeting"
  brokers:
    - "127.0.0.1:9094"

jaeger:
  host: "jaeger"
  port: ":6831"