version: "3.1"

services:
  ocp-meeting-api:
    build: .
    restart: unless-stopped
    networks:
      - ocp-meeting-api-network
    depends_on:
      - postgres
      - kafka
    links:
      - postgres
    ports:
      - "8081:8081" # rest
      - "8082:8082" # grpc
      - "9100:9100" # prometheus

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - ocp-meeting-api-network

  kafka:
    image: confluentinc/cp-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ocp-meeting-api-network

  kafka-ui:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - ocp-meeting-api-network

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./metrics.yml:/etc/metrics/metrics.yml"
    networks:
      - ocp-meeting-api-network

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - "127.0.0.1:6831:6831/udp"
      - "16686:16686"
    networks:
      - ocp-meeting-api-network

volumes:
  pgdata:

networks:
  ocp-meeting-api-network:
    driver: bridge
